# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NoticePopupA' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NoticePopupA
pod 'Firebase/RemoteConfig'
pod 'Firebase/Analytics'

  target 'NoticePopupATests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NoticePopupAUITests' do
    # Pods for testing
  end

end
