# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'covidA' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'Charts'

  # Pods for covidA

  target 'covidATests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'covidAUITests' do
    # Pods for testing
  end

end
