# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpotifySampleB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	
  # Pods for SpotifySampleB
pod 'FirebaseAuth'
pod 'GoogleSignIn', '~> 5.0.3'

  target 'SpotifySampleBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SpotifySampleBUITests' do
    # Pods for testing
  end

end
